-- VIEW REZERWACJE_POTWIERDZONE
CREATE OR REPLACE VIEW view_rezerwacje_potwierdzone
    AS
        SELECT *
        FROM view_rezerwacje_wszystkie rw
        WHERE rw.STATUS = 'P' OR rw.STATUS = 'Z';

SELECT * FROM WYCIECZKI;
SELECT * FROM REZERWACJE;
SELECT * FROM OSOBY;
SELECT * FROM REZERWACJE_LOG;

CALL PRC_DODAJ_REZERWACJE3(6, 5);
CALL PRC_ZMIEN_STATUS_REZERWACJI3(82, 'Z');

CALL PRC_ZMIEN_LICZBE_MIEJSC3(6, 10);