-- TABLE OSOBY
CREATE TABLE OSOBY
(
    ID_OSOBY INT GENERATED ALWAYS AS IDENTITY NOT NULL
  , IMIE VARCHAR2(50)
  , NAZWISKO VARCHAR2(50)
  , PESEL VARCHAR2(11)
  , KONTAKT VARCHAR2(100)
  , CONSTRAINT OSOBY_PK PRIMARY KEY
    (
        ID_OSOBY
    )
    ENABLE
);