-- TABLE WYCIECZKI
CREATE TABLE WYCIECZKI
(
    ID_WYCIECZKI INT GENERATED ALWAYS AS IDENTITY NOT NULL
    , NAZWA VARCHAR2(100)
    , KRAJ VARCHAR2(50)
    , DATA DATE
    , OPIS VARCHAR2(200)
    , LICZBA_MIEJSC INT
    , CONSTRAINT WYCIECZKI_PK PRIMARY KEY
    (
        ID_WYCIECZKI
    )
    ENABLE
);