-- INSERTING INITIAL DATA INTO TABLES

-- TABLE: OSOBY
INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Adam', 'Kowalski', '87654321', 'tel: 6623');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Michal', 'Blumberg', '56652320', 'e-mail: blumber.gmail.com');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Kasia', 'Nowak', '73950372', 'tel: 73943');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Luda', 'Ptuszkina', '74925927', 'tel: 34839');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Piotr', 'Krusiak', '74922848', 'e-mail: piotr.krusiak@gmail.com');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Slawik', 'Marlek', '92832732', 'tel: 39483');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Agata', 'Lumsik', '57393483', 'tel: 2324');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Flora', 'Gusiak', '48394839', 'e-mail: flora@mail.com');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Bartosz', 'Remilek', '34938493', 'tel: 23492');

INSERT INTO OSOBY (IMIE, NAZWISKO, PESEL, KONTAKT)
VALUES ('Swiatlana', 'Luzik', '439384934', 'tel: 3243554');


-- TABLE: WYCIECZKI
INSERT INTO WYCIECZKI (NAZWA, KRAJ, DATA, OPIS, LICZBA_MIEJSC)
VALUES ('Wycieczka do Paryza','Francja',TO_DATE('2016-01-01','YYYY-MM-DD'),'Ciekawa wycieczka ...',3);

INSERT INTO wycieczki (NAZWA, KRAJ, DATA, OPIS, LICZBA_MIEJSC)
VALUES ('Piekny Krakow','Polska',TO_DATE('2017-02-03','YYYY-MM-DD'),'Najciekawa wycieczka ...',2);

INSERT INTO wycieczki (NAZWA, KRAJ, DATA, OPIS, LICZBA_MIEJSC)
VALUES ('Wieliczka','Polska',TO_DATE('2017-03-03','YYYY-MM-DD'),'Zadziwiajaca kopalnia ...',2);

INSERT INTO wycieczki (NAZWA, KRAJ, DATA, OPIS, LICZBA_MIEJSC)
VALUES ('Piekne gory','Polska',TO_DATE('2020-05-12','YYYY-MM-DD'),'Wysokie gory ...',3);

-- TABLE RESERWACJE
INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (3,1,'N');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (3,4,'P');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (3,5,'Z');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (4,6,'P');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (4,7,'A');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (5,8,'Z');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (5,9,'N');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (6,10,'A');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (6,12,'P');

INSERT INTO REZERWACJE(ID_WYCIECZKI, ID_OSOBY, STATUS)
VALUES (6,1,'Z');
