--TABLES
CREATE TABLE OSOBY
(
    ID_OSOBY INT GENERATED ALWAYS AS IDENTITY NOT NULL
  , IMIE VARCHAR2(50)
  , NAZWISKO VARCHAR2(50)
  , PESEL VARCHAR2(11)
  , KONTAKT VARCHAR2(100)
  , CONSTRAINT OSOBY_PK PRIMARY KEY
    (
        ID_OSOBY
    )
    ENABLE
);

CREATE TABLE WYCIECZKI
(
    ID_WYCIECZKI INT GENERATED ALWAYS AS IDENTITY NOT NULL
    , NAZWA VARCHAR2(100)
    , KRAJ VARCHAR2(50)
    , DATA DATE
    , OPIS VARCHAR2(200)
    , LICZBA_MIEJSC INT
    , CONSTRAINT WYCIECZKI_PK PRIMARY KEY
    (
        ID_WYCIECZKI
    )
    ENABLE
);

CREATE TABLE REZERWACJE
(
    NR_REZERWACJI INT GENERATED ALWAYS AS IDENTITY NOT NULL
    , ID_WYCIECZKI INT, ID_OSOBY INT
    , STATUS CHAR(1)
    , CONSTRAINT REZERWACJE_PK PRIMARY KEY
    (
    NR_REZERWACJI
    )
    ENABLE
);

ALTER TABLE REZERWACJE
ADD CONSTRAINT REZERWACJE_FK1 FOREIGN KEY
(
    ID_OSOBY
)
REFERENCES OSOBY
(
    ID_OSOBY
)
ENABLE;

ALTER TABLE REZERWACJE
ADD CONSTRAINT REZERWACJE_FK2 FOREIGN KEY
(
ID_WYCIECZKI
)
REFERENCES WYCIECZKI
(
    ID_WYCIECZKI
)
ENABLE;

ALTER TABLE REZERWACJE
ADD CONSTRAINT REZERWACJE_CHK1 CHECK
(status IN ('N','P','Z','A'))
ENABLE;